version: 1
process_count: 2
timeout: 0.1
logger:
  level: INFO

pipeline:
  - dissector:
      type: dissector
      specific_rules:
        - /opt/ownpipe/dissector/specific
      generic_rules:
        - /opt/ownpipe/dissector/generic/
  - normalizer:       
      type: normalizer
      specific_rules:
        - /opt/ownpipe/normalizer/specific/
      generic_rules:
        - /opt/ownpipe/normalizer/generic/
      regex_mapping: /opt/ownpipe/normalizer/regex_mapping.yml
        
input:
  authjson:
    type: file_input
    logfile_path: /var/log/auth.log
    interval: 1

output:
  authjson:
    type: console_output

